services:
  - type: web
    name: verity-ai
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: VITE_GOOGLE_CLIENT_ID
        sync: false
      - key: APP_ORIGIN
        value: https://verityai-1-h22e.onrender.com
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: OWNER_UNION_ID
        sync: false
    healthCheckPath: /api/health
